### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by alexnedelcu** [bl00mber/react-phone-input-2#103]
I am using SSR and I am getting the following error:

ReferenceError: window is not defined
    at Object.<anonymous> (D:\dev\myproject\node_modules\material-ui-phone-number\dist\index.js:1:1601)
    at Module._compile (module.js:652:30)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\dev\peerleap\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

(function (exports, require, module, __filename, __dirname) { !function(n,e){"object"==typeof exports&&"object"==typeof module?module.exports=e(require("react"),require("@material-ui/core/RootRef"),require("classnames"),require("@material-ui/core/TextField"),require("@material-ui/core/InputAdornment"),require("@material-ui/core/Button"),require("@material-ui/core/Menu"),require("@material-ui/core/Divider"),require("@material-ui/core/NativeSelect"),require("@material-ui/styles/withStyles"),require("@material-ui/core/MenuItem")):"function"==typeof define&&define.amd?define(["react","@material-ui/core/RootRef","classnames","@material-ui/core/TextField","@material-ui/core/InputAdornment","@material-ui/core/Button","@material-ui/core/Menu","@material-ui/core/Divider","@material-ui/core/NativeSelect","@material-ui/styles/withStyles","@material-ui/core/MenuItem"],e):"object"==typeof exports?exports.MaterialUiPhoneNumber=e(require("react"),requir

**Comment by alexnedelcu** [comment]
Ran into this issue on the latest versions (both 2.0.0-beta0 and 1.6.1).

**Comment by alexnedelcu** [comment]
sorry, this is a material ui issue. Does not apply to this repo,
