### ISSUE TITLE
Test failing

### ISSUE THREAD

**Issue by dextel2** [bl00mber/react-phone-input-2#53]
Hello,
I'm running the default test of CRA i.e. `App.test.js` and getting the following error

```
src\App.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'document' of undefined

      at Object.i (node_modules/react-phone-input-2/dist/index.js:2:25894)
      at n (node_modules/react-phone-input-2/dist/index.js:1:476)
      at Object.<anonymous> (node_modules/react-phone-input-2/dist/index.js:1:1890)
      at n (node_modules/react-phone-input-2/dist/index.js:1:476)
      at Object.defineProperty.value (node_modules/react-phone-input-2/dist/index.js:1:563)
      at node_modules/react-phone-input-2/dist/index.js:1:568
      at Object.<anonymous>.r (node_modules/react-phone-input-2/dist/index.js:1:170)
      at Object.<anonymous> (node_modules/react-phone-input-2/dist/index.js:1:346)
```

What could be the possible cause of it?

My `jest.config.js`

```
    "globals" = {
        "window": true,
        "document":true
    }


```

**Comment by awthwathje** [comment]
This project is not covered by any tests.

**Comment by dextel2** [comment]
So, how I do I skip it from tests?

**Comment by awthwathje** [comment]
`src\App.test.js` is not part of the project. Most likely it is a part of Create React App. If you don't want `App.test.js` to be run, you can simply delete this file.

**Comment by dextel2** [comment]
@awthwathje I want that to run, but I want  `react-phone-input-2` to be skipped.
